version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Teste123@456"
    ports:
      - "1433:1433"
    volumes:
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    command:
      - /bin/bash
      - /usr/src/app/entrypoint.sh
  variacaoativofixo.api:
      depends_on:
        - sqlserver
      image: ${DOCKER_REGISTRY-}variacaoativofixoapi
      build:
        context: .
        dockerfile: VariacaoAtivoFixo/Dockerfile